modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mixins]]
config="rocketnautics.mixins.json"

[[mods]]
modId="rocketnautics"
version="1.3.0"
displayName="Create: Rocketnautics"
displayURL="https://github.com"
authors="webyep, LordAret, SSnowly"
description='''
An addon for Create Aeronautics adding Rocket Thrusters!
'''

[[dependencies.rocketnautics]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rocketnautics]]
    modId="create"
    type="required"
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rocketnautics]]
    modId="aeronautics"
    type="required"
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="BOTH"
