modLoader="javafml"
loaderVersion="[2,)"
license="GNU GPL v3"

[[mixins]]
config="rocketnautics.mixins.json"

[[mods]]
modId="rocketnautics"
version="1.3.7"
displayName="Create: Cosmonautics"
displayURL="https://github.com"
authors="webyep, LordAret, SSnowly, M_W_K"
description='''
An addon for Create Aeronautics adding Rocket Thrusters! Now rebranded as Cosmonautics.
'''

[[dependencies.rocketnautics]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rocketnautics]]
    modId="create"
    type="required"
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rocketnautics]]
    modId="aeronautics"
    type="required"
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="BOTH"
