package dev.devce.rocketnautics.content.blocks;

import com.simibubi.create.foundation.blockEntity.SmartBlockEntity;
import com.simibubi.create.foundation.blockEntity.behaviour.BlockEntityBehaviour;
import com.simibubi.create.foundation.blockEntity.behaviour.CenteredSideValueBoxTransform;
import com.simibubi.create.foundation.blockEntity.behaviour.scrollValue.ScrollValueBehaviour;
import dev.devce.rocketnautics.registry.RocketBlockEntities;
import dev.devce.rocketnautics.registry.RocketParticles;
import dev.devce.rocketnautics.registry.RocketTags;
import dev.devce.rocketnautics.RocketConfig;
import dev.ryanhcode.sable.api.block.BlockEntitySubLevelActor;
import dev.ryanhcode.sable.api.physics.force.ForceGroup;
import dev.ryanhcode.sable.api.physics.handle.RigidBodyHandle;
import dev.ryanhcode.sable.sublevel.ServerSubLevel;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.core.HolderLookup;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.chat.Component;
import net.minecraft.util.RandomSource;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.material.Fluids;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.Vec3;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.neoforge.fluids.FluidStack;
import net.neoforged.neoforge.fluids.capability.IFluidHandler;
import net.neoforged.neoforge.fluids.capability.templates.FluidTank;
import org.joml.Vector3d;

import java.util.List;

/**
 * Block Entity for the Rocket Thruster.
 * Handles fuel logic, ignition sequences, physics force application via Sable, 
 * and complex visual/particle effects for the rocket's exhaust plume.
 */
public class RocketThrusterBlockEntity extends SmartBlockEntity implements BlockEntitySubLevelActor, IThruster, com.simibubi.create.api.equipment.goggles.IHaveGoggleInformation {
    private static int getMaxFuelConsumption() { return RocketConfig.SERVER.maxFuelConsumption.get(); }
    private static int getSteamMinFlow() { return RocketConfig.SERVER.steamMinFlow.get(); }
    private static int getIgnitionFlow() { return RocketConfig.SERVER.ignitionFlow.get(); }
    private static final float MIN_THROTTLE_CHANGE = 0.01f;

    public FluidTank fuelTank = new FluidTank(1000, fluid -> true);
    public ScrollValueBehaviour minThrust;
    public ScrollValueBehaviour maxThrust;

    @Override
    public ScrollValueBehaviour getThrustPower() {
        return maxThrust;
    }

    /** Physics force group for all rocket-related thrust. */
    public static final dev.ryanhcode.sable.api.physics.force.ForceGroup ROCKET_FORCE = new dev.ryanhcode.sable.api.physics.force.ForceGroup(
            Component.literal("Rocket Thrust"),
            Component.literal("Thrust generated by rocket engines"),
            0x3366FF,
            true
    );
    
    public int ignitionTicks = 0;
    public boolean currentlyBurning = false;
    public float fuelThrottle = 0.0f;
    private float internalFlow = 0.0f;
    private int startupTicks = 0; 
    public int currentFuelUsage = 0;
    private int totalAvailableFuel = 0;
    private float currentIspMultiplier = 1.0f;
    private float currentEfficiencyMultiplier = 1.0f;
    private int burnoutDelay = 0;
    private boolean steamMode = false;

    public int getWarmupTime() {
        return 40;
    }

    public RocketThrusterBlockEntity(BlockPos pos, BlockState state) {
        super(RocketBlockEntities.ROCKET_THRUSTER.get(), pos, state);
    }

    protected RocketThrusterBlockEntity(BlockEntityType<?> type, BlockPos pos, BlockState state) {
        super(type, pos, state);
    }

    @Override
    public void addBehaviours(List<BlockEntityBehaviour> behaviours) {
        minThrust = new ScrollValueBehaviour(
                Component.translatable("gui.rocketnautics.min_thrust"), 
                this, 
                new CenteredSideValueBoxTransform((state, direction) -> direction != state.getValue(RocketThrusterBlock.FACING))
        );
        minThrust.between(0, 50);
        minThrust.withFormatter(v -> (v * 10) + " N");
        minThrust.setValue(0);
        
        maxThrust = new ScrollValueBehaviour(
                Component.translatable("gui.rocketnautics.max_thrust"), 
                this, 
                new CenteredSideValueBoxTransform((state, direction) -> direction != state.getValue(RocketThrusterBlock.FACING))
        );
        maxThrust.between(0, 50);
        maxThrust.withFormatter(v -> (v * 10) + " N");
        maxThrust.setValue(10);
        
        behaviours.add(minThrust);
        behaviours.add(maxThrust);
    }

    /**
     * Calculates the current thrust output in Newtons.
     * @return Thrust value based on throttle and min/max settings.
     */
    public int getCurrentPower() {
        if (!isActive()) return 0;
        
        int min = minThrust.getValue();
        int max = maxThrust.getValue();
        if (min > max) min = max;
        
        return (int) (min + (max - min) * fuelThrottle);
    }

    private float getVisualBoost() {
        return 1.0f + (fuelThrottle * 0.5f);
    }

    public Vector3d getParticleDirection() {
        Direction nozzle = getThrustDirection();
        return new Vector3d(nozzle.getStepX(), nozzle.getStepY(), nozzle.getStepZ());
    }

    /**
     * Main ticking logic for the thruster.
     * Handles particle spawning, camera shake, entity damage, and block melting.
     */
    public static void tick(Level level, BlockPos pos, BlockState state, RocketThrusterBlockEntity blockEntity) {
        if (!level.isClientSide) {
            blockEntity.updateActiveState();
        }

        blockEntity.tick();
        boolean active = blockEntity.isActive();
        
        if (level.isClientSide()) {
            // Client-side visual and auditory effects
            blockEntity.updateSound();
            
            if (active) {
                Vector3d pDir = blockEntity.getParticleDirection();
                double x = pos.getX() + 0.5 + pDir.x() * 0.7;
                double y = pos.getY() + 0.5 + pDir.y() * 0.7;
                double z = pos.getZ() + 0.5 + pDir.z() * 0.7;

                RandomSource random = level.getRandom();
                int power = blockEntity.getCurrentPower();
                int visualPower = (int)(power * 2.85f);
                float boost = blockEntity.getVisualBoost();

                // Calculate exhaust plume distance and collision with blocks
                net.minecraft.world.phys.Vec3 start = new net.minecraft.world.phys.Vec3(x, y, z);
                double maxSearchDist = 15.0 + (visualPower / 10.0);
                net.minecraft.world.phys.Vec3 end = start.add(pDir.x() * maxSearchDist, pDir.y() * maxSearchDist, pDir.z() * maxSearchDist);
                net.minecraft.world.phys.BlockHitResult hit = level.clip(new net.minecraft.world.level.ClipContext(start, end, net.minecraft.world.level.ClipContext.Block.COLLIDER, net.minecraft.world.level.ClipContext.Fluid.NONE, net.minecraft.world.phys.shapes.CollisionContext.empty()));
                
                double hitDist = maxSearchDist;
                boolean hitBlock = false;
                net.minecraft.world.phys.Vec3 hitPos = end;
                if (hit.getType() == net.minecraft.world.phys.HitResult.Type.BLOCK) {
                    hitDist = start.distanceTo(hit.getLocation());
                    hitBlock = true;
                    hitPos = hit.getLocation();
                }

                // Spawn exhaust particles based on power and distance
                int plumeCount = 1 + (visualPower / 5);
                float baseSpeedMult = 0.8f + (visualPower / 100.0f) * 1.2f;
                float maxSpeedMult = (float)(hitDist / 15.0);
                float actualSpeedMult = Math.min(baseSpeedMult, maxSpeedMult);
            
                for (int i = 0; i < plumeCount; i++) {
                    double speedX = pDir.x() * (1.5 + random.nextDouble() * 1.0) * boost * actualSpeedMult + (random.nextDouble() - 0.5) * 0.2;
                    double speedY = pDir.y() * (1.5 + random.nextDouble() * 1.0) * boost * actualSpeedMult + (random.nextDouble() - 0.5) * 0.2;
                    double speedZ = pDir.z() * (1.5 + random.nextDouble() * 1.0) * boost * actualSpeedMult + (random.nextDouble() - 0.5) * 0.2;
                    
                    var particle = (blockEntity.ignitionTicks < blockEntity.getWarmupTime()) ? 
                            RocketParticles.PLUME.get() : 
                            RocketParticles.BLUE_FLAME.get();
                    
                    level.addParticle(particle, x, y, z, speedX, speedY, speedZ);
                }
                
                // Secondary effects: ground smoke and camera shake
                if (active) {
                    if (hitBlock && random.nextFloat() < (visualPower / 50.0f)) {
                        for (int i = 0; i < (1 + visualPower / 5); i++) {
                            net.minecraft.world.phys.Vec3 normal = new net.minecraft.world.phys.Vec3(hit.getDirection().getStepX(), hit.getDirection().getStepY(), hit.getDirection().getStepZ());
                            net.minecraft.world.phys.Vec3 randomDir = new net.minecraft.world.phys.Vec3(random.nextDouble() - 0.5, random.nextDouble() - 0.5, random.nextDouble() - 0.5).normalize();
                            net.minecraft.world.phys.Vec3 spreadDir = randomDir.subtract(normal.scale(randomDir.dot(normal))).normalize();
                            double speed = 0.5 + random.nextDouble() * 1.5;
                            level.addParticle(RocketParticles.JET_SMOKE.get(), hitPos.x, hitPos.y, hitPos.z, spreadDir.x * speed, spreadDir.y * speed, spreadDir.z * speed);
                        }
                    } else if (!hitBlock && random.nextFloat() < (visualPower / 100.0f)) {
                        double smokeX = x + pDir.x() * hitDist * 0.8;
                        double smokeY = y + pDir.y() * hitDist * 0.8;
                        double smokeZ = z + pDir.z() * hitDist * 0.8;
                        for (int i = 0; i < (1 + visualPower / 10); i++) {
                            double speedX = pDir.x() * (0.8 + random.nextDouble() * 0.5) + (random.nextDouble() - 0.5) * 0.8;
                            double speedY = pDir.y() * (0.8 + random.nextDouble() * 0.5) + (random.nextDouble() - 0.5) * 0.8;
                            double speedZ = pDir.z() * (0.8 + random.nextDouble() * 0.5) + (random.nextDouble() - 0.5) * 0.8;
                            level.addParticle(RocketParticles.JET_SMOKE.get(), smokeX, smokeY, smokeZ, speedX, speedY, speedZ);
                        }
                    }

                    net.minecraft.client.Minecraft mc = net.minecraft.client.Minecraft.getInstance();
                    if (mc.player != null) {
                        double distSq = mc.player.distanceToSqr(pos.getX() + 0.5, pos.getY() + 0.5, pos.getZ() + 0.5);
                        double radius = RocketConfig.CLIENT.shakeRadius.get();
                        if (distSq < (radius * radius)) {
                            float distanceFactor = 1.0f - (float) (Math.sqrt(distSq) / radius);
                            float powerFactor = blockEntity.fuelThrottle;
                            dev.devce.rocketnautics.client.CameraShakeHandler.addShake(distanceFactor * powerFactor * RocketConfig.CLIENT.shakeIntensity.get().floatValue());
                        }
                    }
                }
            }
        }
        
        // Handle ignition and warmup timing
        if (active) {
            if (blockEntity.ignitionTicks < 100) blockEntity.ignitionTicks++;
        } else {
            if (blockEntity.ignitionTicks > 0) blockEntity.ignitionTicks--;
        }
        
        // Apply world damage: pushing entities and melting blocks
        if (active) {
            Direction nozzle = blockEntity.getThrustDirection();
            int power = blockEntity.getCurrentPower();
            int visualPower = (int)(power * 2.85f);
            double reach = 1.0 + (visualPower / 5.0);
            Vec3 start = Vec3.atCenterOf(pos).add(nozzle.getStepX() * 0.5, nozzle.getStepY() * 0.5, nozzle.getStepZ() * 0.5);
            Vec3 end = start.add(nozzle.getStepX() * reach, nozzle.getStepY() * reach, nozzle.getStepZ() * reach);
            AABB damageArea = new AABB(start, end).inflate(0.5);

            List<LivingEntity> affectedEntities = level.getEntitiesOfClass(LivingEntity.class, damageArea);
            affectedEntities.forEach(entity -> {
                if (entity.isAlive()) {
                    double pushStrength = (visualPower / 150.0);
                    entity.push(nozzle.getStepX() * pushStrength, nozzle.getStepY() * pushStrength, nozzle.getStepZ() * pushStrength);
                    if (!level.isClientSide) {
                        entity.hurtMarked = true;
                    }
                }
            });
            
            if (!level.isClientSide && level.getGameTime() % 10 == 0) {
                // Melt blocks in the exhaust path
                for (int dist = 1; dist <= 3; dist++) {
                    BlockPos targetPos = pos.relative(nozzle, dist);
                    BlockState targetState = level.getBlockState(targetPos);
                    
                    if (targetState.isAir()) continue;
                    
                    float hardness = targetState.getDestroySpeed(level, targetPos);
                    if (hardness < 0 || hardness > 10.0f) break;
                    
                    if (level.random.nextInt(100) < (visualPower * 2)) {
                        if (targetState.is(Blocks.LAVA)) break;
                        
                        if (targetState.is(Blocks.MAGMA_BLOCK)) {
                            level.setBlock(targetPos, Blocks.LAVA.defaultBlockState(), 3);
                        } else if (!targetState.is(Blocks.AIR)) {
                            level.setBlock(targetPos, Blocks.MAGMA_BLOCK.defaultBlockState(), 3);
                        }
                    }
                    
                    if (targetState.isCollisionShapeFullBlock(level, targetPos)) break;
                }
                
                // Burn entities in the plume
                affectedEntities.forEach(entity -> {
                    if (entity.isAlive()) {
                        float damage = (float) (visualPower / 10.0);
                        entity.hurt(level.damageSources().lava(), damage);
                        entity.setRemainingFireTicks(entity.getRemainingFireTicks() + 40);
                    }
                });
            }
        }
    }

    /**
     * Physics tick called by Sable to apply thrust forces.
     * Thrust is applied as an impulse at the block's world position.
     */
    @Override
    public void sable$physicsTick(ServerSubLevel serverSubLevel, RigidBodyHandle handle, double deltaTime) {
        if (!isActive()) return;

        Direction facing = getThrustDirection();
        Direction pushDirection = facing.getOpposite(); // Thrust pushes in opposite direction of nozzle
        double currentThrust = getCurrentPower() * 10.0;
        
        Vector3d thrustVector = new Vector3d(
                pushDirection.getStepX() * currentThrust,
                pushDirection.getStepY() * currentThrust,
                pushDirection.getStepZ() * currentThrust
        );

        Vector3d blockCenter = new Vector3d(worldPosition.getX() + 0.5, worldPosition.getY() + 0.5, worldPosition.getZ() + 0.5);
        handle.applyImpulseAtPoint(blockCenter, thrustVector.mul(deltaTime));
    }

    @Override
    public void remove() {
        super.remove();
        if (level != null && level.isClientSide) {
            ClientLogic.stopSound(this);
        }
    }

    private Object soundInstance;

    private void updateSound() {
        if (level.isClientSide) {
            ClientLogic.updateSound(this);
        }
    }

    private static class ClientLogic {
        private static void updateSound(RocketThrusterBlockEntity be) {
            if (!be.isActive()) {
                stopSound(be);
                return;
            }

            if (be.soundInstance == null) {
                startSound(be);
            }
        }

        private static void startSound(RocketThrusterBlockEntity be) {
            net.minecraft.client.Minecraft mc = net.minecraft.client.Minecraft.getInstance();
            ThrusterSoundInstance instance = new ThrusterSoundInstance(be);
            mc.getSoundManager().play(instance);
            be.soundInstance = instance;
        }

        private static void stopSound(RocketThrusterBlockEntity be) {
            if (be.soundInstance instanceof ThrusterSoundInstance instance) {
                instance.stopSound();
                be.soundInstance = null;
            }
        }
    }

    public boolean isActive() {
        return currentlyBurning;
    }

    protected void updateActiveState() {
        if (level == null || level.isClientSide) return;

        boolean wasBurning = this.currentlyBurning;
        float oldThrottle = this.fuelThrottle;
        int oldUsage = this.currentFuelUsage;
        int oldFuel = this.totalAvailableFuel;

        updateFuelProperties();
        
        int targetConsumption = (int) (getMaxFuelConsumption() * currentEfficiencyMultiplier);
        int actuallyDrained = attemptFuelDrain(targetConsumption);

        if (dev.devce.rocketnautics.RocketConfig.SERVER.enableEngineDebugLogging.get() && level.getGameTime() % 20 == 0) {
            String fluidName = fuelTank.getFluid().isEmpty() ? "Empty" : net.minecraft.core.registries.BuiltInRegistries.FLUID.getKey(fuelTank.getFluid().getFluid()).toString();
            dev.devce.rocketnautics.RocketNautics.LOGGER.info("Engine at {}: Fluid={}, Amount={}mB, Drained={}mB, Valid={}", 
                worldPosition, fluidName, fuelTank.getFluidAmount(), actuallyDrained, isRocketFuel(fuelTank.getFluid()));
        }

        
        float targetFlow = actuallyDrained / (float) Math.max(1, targetConsumption);
        
        
        if (targetFlow > 0) {
            if (startupTicks < 10) { 
                startupTicks++;
                
                float steamCap = (getIgnitionFlow() - 1.0f) / (float)getMaxFuelConsumption();
                this.internalFlow = net.minecraft.util.Mth.lerp(0.2f, this.internalFlow, Math.min(targetFlow, steamCap));
            } else {
                
                this.internalFlow = net.minecraft.util.Mth.lerp(0.5f, this.internalFlow, targetFlow);
            }
        } else {
            
            this.internalFlow = net.minecraft.util.Mth.lerp(0.05f, this.internalFlow, 0.00f);
            if (this.internalFlow < 0.001f) {
                this.internalFlow = 0;
                if (burnoutDelay <= 0) startupTicks = 0; 
            }
        }

        this.fuelThrottle = internalFlow;

        
        float effectiveFlow = internalFlow * getMaxFuelConsumption();

        if (effectiveFlow >= (getIgnitionFlow() - 0.5f)) {
            if (startupTicks >= 10 || wasBurning) {
                this.currentlyBurning = true;
                this.steamMode = false;
                this.burnoutDelay = 10;
                if (startupTicks < 10) startupTicks = 10; 
            } else {
                this.currentlyBurning = false;
                this.steamMode = true;
            }
        } else if (effectiveFlow >= getSteamMinFlow() || (targetFlow > 0 && startupTicks < 10)) {
            this.currentlyBurning = false;
            this.steamMode = true;
            this.burnoutDelay = 0;
        } else {
            if (burnoutDelay > 0) {
                burnoutDelay--;
            } else {
                this.currentlyBurning = false;
                this.steamMode = false;
                startupTicks = 0; 
            }
        }

        this.currentFuelUsage = actuallyDrained;
        this.totalAvailableFuel = fuelTank.getFluidAmount();
        
        if (wasBurning != currentlyBurning || Math.abs(oldThrottle - fuelThrottle) > MIN_THROTTLE_CHANGE || oldUsage != currentFuelUsage || Math.abs(oldFuel - totalAvailableFuel) > 50) {
            sendData();
            setChanged();
        }
    }

    private void updateFuelProperties() {
        FluidStack stack = fuelTank.getFluid();
        if (stack.isEmpty() || !isRocketFuel(stack)) {
            currentIspMultiplier = 1.0f;
            currentEfficiencyMultiplier = 1.0f;
            return;
        }

        String fluidId = net.minecraft.core.registries.BuiltInRegistries.FLUID.getKey(stack.getFluid()).toString().toLowerCase();
        
        if (fluidId.contains("kerosene")) {
            currentIspMultiplier = 1.4f;      
            currentEfficiencyMultiplier = 0.5f; 
        } else if (fluidId.contains("diesel") || fluidId.contains("fuel_oil") || fluidId.contains("lpg")) {
            currentIspMultiplier = 1.2f;
            currentEfficiencyMultiplier = 0.7f;
        } else if (fluidId.contains("gasoline") || fluidId.contains("petrol")) {
            currentIspMultiplier = 1.1f;
            currentEfficiencyMultiplier = 0.8f;
        } else {
            currentIspMultiplier = 1.0f;
            currentEfficiencyMultiplier = 1.0f;
        }
    }

    private boolean isRocketFuel(FluidStack stack) {
        if (stack.isEmpty()) return false;
        if (stack.getFluid().isSame(net.minecraft.world.level.material.Fluids.LAVA)) return true;
        if (stack.is(RocketTags.Fluids.ROCKET_FUEL)) return true;
        
        String id = net.minecraft.core.registries.BuiltInRegistries.FLUID.getKey(stack.getFluid()).toString();
        return id.contains("tfmg") && (id.contains("kerosene") || id.contains("diesel") || id.contains("gasoline") || id.contains("fuel_oil") || id.contains("lpg"));
    }

    private int attemptFuelDrain(int amount) {
        if (fuelTank.getFluidAmount() > 0 && isRocketFuel(fuelTank.getFluid())) {
            int toDrain = Math.min(fuelTank.getFluidAmount(), amount);
            return fuelTank.drain(toDrain, IFluidHandler.FluidAction.EXECUTE).getAmount();
        }
        return 0;
    }

    @Override
    protected void write(CompoundTag tag, HolderLookup.Provider registries, boolean clientPacket) {
        super.write(tag, registries, clientPacket);
        tag.putBoolean("Burning", currentlyBurning);
        tag.putInt("IgnitionTicks", ignitionTicks);
        tag.putFloat("FuelThrottle", fuelThrottle);
        tag.putInt("FuelUsage", currentFuelUsage);
        tag.putBoolean("SteamMode", steamMode);
        tag.putInt("StartupTicks", startupTicks);
        tag.putInt("TotalFuel", totalAvailableFuel);
        tag.putFloat("IspMult", currentIspMultiplier);
        tag.put("FuelTank", fuelTank.writeToNBT(registries, new CompoundTag()));
    }

    @Override
    protected void read(CompoundTag tag, HolderLookup.Provider registries, boolean clientPacket) {
        super.read(tag, registries, clientPacket);
        currentlyBurning = tag.getBoolean("Burning");
        ignitionTicks = tag.getInt("IgnitionTicks");
        fuelThrottle = tag.getFloat("FuelThrottle");
        currentFuelUsage = tag.getInt("FuelUsage");
        steamMode = tag.getBoolean("SteamMode");
        startupTicks = tag.getInt("StartupTicks");
        totalAvailableFuel = tag.getInt("TotalFuel");
        currentIspMultiplier = tag.getFloat("IspMult");
        if (tag.contains("FuelTank")) {
            fuelTank.readFromNBT(registries, tag.getCompound("FuelTank"));
        }
    }

    public Direction getThrustDirection() {
        return getBlockState().getValue(RocketThrusterBlock.FACING);
    }

    @Override
    public boolean addToGoggleTooltip(List<Component> tooltip, boolean isPlayerSneaking) {
        tooltip.add(Component.literal("    ").append(Component.translatable(getBlockState().getBlock().getDescriptionId()).withStyle(net.minecraft.ChatFormatting.GOLD)));
        
        tooltip.add(Component.literal("  ").append(Component.translatable("rocketnautics.goggles.status")).append(": ")
                .append(isActive() ? Component.translatable("rocketnautics.goggles.active").withStyle(net.minecraft.ChatFormatting.GREEN) : 
                       (steamMode ? Component.literal("Steam (Warmup)").withStyle(net.minecraft.ChatFormatting.YELLOW) : 
                                   Component.translatable("rocketnautics.goggles.inactive").withStyle(net.minecraft.ChatFormatting.RED))));
        
        int power = getCurrentPower();
        tooltip.add(Component.literal("  ").append(Component.translatable("rocketnautics.goggles.thrust")).append(": ")
                .append(Component.literal(power * 10 + " N").withStyle(net.minecraft.ChatFormatting.GOLD)));
        
        
        int flowPerSecond = currentFuelUsage * 20;
        tooltip.add(Component.literal("  Flow Rate: ").append(Component.literal(flowPerSecond + " mB/s").withStyle(net.minecraft.ChatFormatting.AQUA)));

        if (totalAvailableFuel > 0) {
            String fuelName = fuelTank.getFluid().getDisplayName().getString();
            tooltip.add(Component.literal("  ").append(Component.translatable("rocketnautics.goggles.fuel")).append(": ")
                    .append(Component.literal(fuelName + " (" + totalAvailableFuel + " mB)").withStyle(net.minecraft.ChatFormatting.AQUA)));
        }

        if (currentIspMultiplier > 1.01f) {
            tooltip.add(Component.literal("  Fuel Quality: ").append(Component.literal(String.format("+%.0f%% Efficiency", (currentIspMultiplier - 1.0f) * 100)).withStyle(net.minecraft.ChatFormatting.GREEN)));
        }
        
        return true;
    }
    public int getStartupTicks() { return startupTicks; }
    public int getBurnoutDelay() { return burnoutDelay; }
    public float getCurrentIspMultiplier() { return currentIspMultiplier; }
    public float getCurrentEfficiencyMultiplier() { return currentEfficiencyMultiplier; }
    public boolean isSteamMode() { return steamMode; }
}
