package dev.devce.rocketnautics.content.blocks;

import com.simibubi.create.foundation.blockEntity.SmartBlockEntity;
import com.simibubi.create.foundation.blockEntity.behaviour.BlockEntityBehaviour;
import com.simibubi.create.foundation.blockEntity.behaviour.CenteredSideValueBoxTransform;
import com.simibubi.create.foundation.blockEntity.behaviour.scrollValue.ScrollValueBehaviour;
import dev.devce.rocketnautics.registry.RocketBlockEntities;
import dev.devce.rocketnautics.registry.RocketParticles;
import dev.ryanhcode.sable.api.block.BlockEntitySubLevelActor;
import dev.ryanhcode.sable.api.physics.force.ForceGroup;
import dev.ryanhcode.sable.api.physics.handle.RigidBodyHandle;
import dev.ryanhcode.sable.sublevel.ServerSubLevel;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.core.HolderLookup;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.chat.Component;
import net.minecraft.util.RandomSource;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.material.Fluids;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.Vec3;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.neoforge.fluids.FluidStack;
import net.neoforged.neoforge.fluids.capability.IFluidHandler;
import net.neoforged.neoforge.fluids.capability.templates.FluidTank;
import org.joml.Vector3d;

import java.util.List;

public class RocketThrusterBlockEntity extends SmartBlockEntity implements BlockEntitySubLevelActor, IThruster, com.simibubi.create.api.equipment.goggles.IHaveGoggleInformation {
    public FluidTank fuelTank = new FluidTank(1000, fluid -> fluid.getFluid().isSame(Fluids.LAVA));
    public ScrollValueBehaviour minThrust;
    public ScrollValueBehaviour maxThrust;
    
    @Override
    public ScrollValueBehaviour getThrustPower() {
        return maxThrust;
    }

    public static final ForceGroup ROCKET_FORCE = new ForceGroup(
            Component.literal("Rocket Thrust"),
            Component.literal("Thrust generated by rocket engines"),
            0x3366FF,
            true
    );

    public int ignitionTicks = 0;
    public boolean currentlyBurning = false;
    public float fuelThrottle = 0.0f;
    public int currentFuelUsage = 0;

    public int getWarmupTime() {
        return 40;
    }

    public RocketThrusterBlockEntity(BlockPos pos, BlockState state) {
        super(RocketBlockEntities.ROCKET_THRUSTER.get(), pos, state);
    }

    protected RocketThrusterBlockEntity(BlockEntityType<?> type, BlockPos pos, BlockState state) {
        super(type, pos, state);
    }

    @Override
    public void addBehaviours(List<BlockEntityBehaviour> behaviours) {
        minThrust = new ScrollValueBehaviour(
                Component.translatable("gui.rocketnautics.min_thrust"), 
                this, 
                new CenteredSideValueBoxTransform((state, direction) -> direction != state.getValue(RocketThrusterBlock.FACING))
        );
        minThrust.between(0, 50);
        minThrust.withFormatter(v -> (v * 10) + " N");
        minThrust.setValue(0);
        
        maxThrust = new ScrollValueBehaviour(
                Component.translatable("gui.rocketnautics.max_thrust"), 
                this, 
                new CenteredSideValueBoxTransform((state, direction) -> direction != state.getValue(RocketThrusterBlock.FACING))
        );
        maxThrust.between(0, 50);
        maxThrust.withFormatter(v -> (v * 10) + " N");
        maxThrust.setValue(10);
        
        behaviours.add(minThrust);
        behaviours.add(maxThrust);
    }

    public int getCurrentPower() {
        if (!isActive()) return 0;
        
        int min = minThrust.getValue();
        int max = maxThrust.getValue();
        if (min > max) min = max;
        
        return (int) (min + (max - min) * fuelThrottle);
    }

    private float getVisualBoost() {
        return 1.0f + (fuelThrottle * 0.5f);
    }

    public Vector3d getParticleDirection() {
        Direction nozzle = getThrustDirection();
        return new Vector3d(nozzle.getStepX(), nozzle.getStepY(), nozzle.getStepZ());
    }

    public static void tick(Level level, BlockPos pos, BlockState state, RocketThrusterBlockEntity blockEntity) {
        if (!level.isClientSide) {
            blockEntity.updateActiveState();
        }

        blockEntity.tick();
        
        if (level.isClientSide()) {
            blockEntity.updateSound();
            
            if (blockEntity.isActive()) {
                Direction nozzle = blockEntity.getThrustDirection();
                Vector3d pDir = blockEntity.getParticleDirection();
                
                double x = pos.getX() + 0.5 + pDir.x() * 0.7;
                double y = pos.getY() + 0.5 + pDir.y() * 0.7;
                double z = pos.getZ() + 0.5 + pDir.z() * 0.7;

                RandomSource random = level.getRandom();
                int power = blockEntity.getCurrentPower();
                int visualPower = (int)(power * 2.85f);

                int plumeCount = 1 + (visualPower / 5);
                float boost = blockEntity.getVisualBoost();
                float thrustSpeedMult = 0.8f + (visualPower / 100.0f) * 1.2f;
            
                for (int i = 0; i < plumeCount; i++) {
                    double speedX = pDir.x() * (1.5 + random.nextDouble() * 1.0) * boost * thrustSpeedMult + (random.nextDouble() - 0.5) * 0.4;
                    double speedY = pDir.y() * (1.5 + random.nextDouble() * 1.0) * boost * thrustSpeedMult + (random.nextDouble() - 0.5) * 0.4;
                    double speedZ = pDir.z() * (1.5 + random.nextDouble() * 1.0) * boost * thrustSpeedMult + (random.nextDouble() - 0.5) * 0.4;
                    
                    var particle = (blockEntity.ignitionTicks < blockEntity.getWarmupTime()) ? 
                            RocketParticles.PLUME.get() : 
                            RocketParticles.BLUE_FLAME.get();
                    
                    level.addParticle(particle, x, y, z, speedX, speedY, speedZ);
                }
                
                if (random.nextFloat() < (visualPower / 100.0f)) {
                    double smokeX = pos.getX() + 0.5 + pDir.x() * 2.5;
                    double smokeY = pos.getY() + 0.5 + pDir.y() * 2.5;
                    double smokeZ = pos.getZ() + 0.5 + pDir.z() * 2.5;
                    
                    for (int i = 0; i < (1 + visualPower / 10); i++) {
                        double speedX = pDir.x() * (0.8 + random.nextDouble() * 0.5) + (random.nextDouble() - 0.5) * 0.8;
                        double speedY = pDir.y() * (0.8 + random.nextDouble() * 0.5) + (random.nextDouble() - 0.5) * 0.8;
                        double speedZ = pDir.z() * (0.8 + random.nextDouble() * 0.5) + (random.nextDouble() - 0.5) * 0.8;
                        level.addParticle(RocketParticles.JET_SMOKE.get(), smokeX, smokeY, smokeZ, speedX, speedY, speedZ);
                    }
                }
            }
        }
        
        if (blockEntity.isActive()) {
            if (blockEntity.ignitionTicks < 100) blockEntity.ignitionTicks++;
        } else {
            if (blockEntity.ignitionTicks > 0) blockEntity.ignitionTicks--;
        }
        
        if (blockEntity.isActive()) {
            Direction nozzle = blockEntity.getThrustDirection();
            int power = blockEntity.getCurrentPower();
            int visualPower = (int)(power * 2.85f);
            double reach = 1.0 + (visualPower / 5.0);
            Vec3 start = Vec3.atCenterOf(pos).add(nozzle.getStepX() * 0.5, nozzle.getStepY() * 0.5, nozzle.getStepZ() * 0.5);
            Vec3 end = start.add(nozzle.getStepX() * reach, nozzle.getStepY() * reach, nozzle.getStepZ() * reach);
            AABB damageArea = new AABB(start, end).inflate(0.5);
            
            level.getEntitiesOfClass(LivingEntity.class, damageArea).forEach(entity -> {
                if (entity.isAlive()) {
                    double pushStrength = (visualPower / 150.0);
                    entity.push(nozzle.getStepX() * pushStrength, nozzle.getStepY() * pushStrength, nozzle.getStepZ() * pushStrength);
                    if (!level.isClientSide) {
                        entity.hurtMarked = true;
                    }
                }
            });
            
            if (!level.isClientSide && level.getGameTime() % 10 == 0) {
                for (int dist = 1; dist <= 3; dist++) {
                    BlockPos targetPos = pos.relative(nozzle, dist);
                    BlockState targetState = level.getBlockState(targetPos);
                    
                    if (targetState.isAir()) continue;
                    
                    float hardness = targetState.getDestroySpeed(level, targetPos);
                    if (hardness < 0 || hardness > 10.0f) break;
                    
                    if (level.random.nextInt(100) < (visualPower * 2)) {
                        if (targetState.is(Blocks.LAVA)) break;
                        
                        if (targetState.is(Blocks.MAGMA_BLOCK)) {
                            level.setBlock(targetPos, Blocks.LAVA.defaultBlockState(), 3);
                        } else if (!targetState.is(Blocks.AIR)) {
                            level.setBlock(targetPos, Blocks.MAGMA_BLOCK.defaultBlockState(), 3);
                        }
                    }
                    
                    if (targetState.isCollisionShapeFullBlock(level, targetPos)) break;
                }
                
                level.getEntitiesOfClass(LivingEntity.class, damageArea).forEach(entity -> {
                    if (entity.isAlive()) {
                        float damage = (float) (visualPower / 10.0);
                        entity.hurt(level.damageSources().lava(), damage);
                        entity.setRemainingFireTicks(entity.getRemainingFireTicks() + 40);
                    }
                });
            }
        }
    }

    @Override
    public void sable$physicsTick(ServerSubLevel serverSubLevel, RigidBodyHandle handle, double deltaTime) {
        if (!isActive()) return;

        Direction facing = getThrustDirection();
        Direction pushDirection = facing.getOpposite();
        double currentThrust = getCurrentPower() * 10.0;
        
        Vector3d thrustVector = new Vector3d(
                pushDirection.getStepX() * currentThrust,
                pushDirection.getStepY() * currentThrust,
                pushDirection.getStepZ() * currentThrust
        );

        Vector3d blockCenter = new Vector3d(worldPosition.getX() + 0.5, worldPosition.getY() + 0.5, worldPosition.getZ() + 0.5);
        handle.applyImpulseAtPoint(blockCenter, thrustVector.mul(deltaTime));
    }

    @Override
    public void remove() {
        super.remove();
        if (level != null && level.isClientSide) {
            ClientLogic.stopSound(this);
        }
    }

    private Object soundInstance;

    private void updateSound() {
        if (level.isClientSide) {
            ClientLogic.updateSound(this);
        }
    }

    private static class ClientLogic {
        private static void updateSound(RocketThrusterBlockEntity be) {
            if (!be.isActive()) {
                stopSound(be);
                return;
            }

            if (be.soundInstance == null) {
                startSound(be);
            }
        }

        private static void startSound(RocketThrusterBlockEntity be) {
            net.minecraft.client.Minecraft mc = net.minecraft.client.Minecraft.getInstance();
            ThrusterSoundInstance instance = new ThrusterSoundInstance(be);
            mc.getSoundManager().play(instance);
            be.soundInstance = instance;
        }

        private static void stopSound(RocketThrusterBlockEntity be) {
            if (be.soundInstance instanceof ThrusterSoundInstance instance) {
                instance.stopSound();
                be.soundInstance = null;
            }
        }
    }

    public boolean isActive() {
        return currentlyBurning;
    }

    protected void updateActiveState() {
        if (level == null || level.isClientSide) return;

        boolean wasBurning = this.currentlyBurning;
        float oldThrottle = this.fuelThrottle;

        int maxConsumption = 40; 
        
        int actuallyDrained = 0;
        
        if (fuelTank.getFluidAmount() > 0) {
            int toDrain = Math.min(fuelTank.getFluidAmount(), maxConsumption);
            actuallyDrained = fuelTank.drain(toDrain, IFluidHandler.FluidAction.EXECUTE).getAmount();
        }
        
        if (actuallyDrained < maxConsumption) {
            int needed = maxConsumption - actuallyDrained;
            actuallyDrained += drainFromAdjacent(needed);
        }

        int oldUsage = this.currentFuelUsage;
        this.fuelThrottle = actuallyDrained / (float) maxConsumption;
        this.currentlyBurning = actuallyDrained > 0;
        this.currentFuelUsage = actuallyDrained;
        
        if (wasBurning != currentlyBurning || Math.abs(oldThrottle - fuelThrottle) > 0.1f || oldUsage != currentFuelUsage) {
            sendData();
            setChanged();
        }
    }

    private int drainFromAdjacent(int amount) {
        Direction back = getThrustDirection().getOpposite();
        BlockPos tankPos = worldPosition.relative(back);
        var fluidHandler = level.getCapability(Capabilities.FluidHandler.BLOCK, tankPos, getThrustDirection());
        
        if (fluidHandler != null) {
            var drained = fluidHandler.drain(new FluidStack(Fluids.LAVA, amount), IFluidHandler.FluidAction.EXECUTE);
            return drained.getAmount();
        }
        return 0;
    }

    @Override
    protected void write(CompoundTag tag, HolderLookup.Provider registries, boolean clientPacket) {
        super.write(tag, registries, clientPacket);
        tag.putBoolean("Burning", currentlyBurning);
        tag.putInt("IgnitionTicks", ignitionTicks);
        tag.putFloat("FuelThrottle", fuelThrottle);
        tag.putInt("FuelUsage", currentFuelUsage);
        tag.put("FuelTank", fuelTank.writeToNBT(registries, new CompoundTag()));
    }

    @Override
    protected void read(CompoundTag tag, HolderLookup.Provider registries, boolean clientPacket) {
        super.read(tag, registries, clientPacket);
        currentlyBurning = tag.getBoolean("Burning");
        ignitionTicks = tag.getInt("IgnitionTicks");
        fuelThrottle = tag.getFloat("FuelThrottle");
        currentFuelUsage = tag.getInt("FuelUsage");
        if (tag.contains("FuelTank")) {
            fuelTank.readFromNBT(registries, tag.getCompound("FuelTank"));
        }
    }

    public Direction getThrustDirection() {
        return getBlockState().getValue(RocketThrusterBlock.FACING);
    }

    @Override
    public boolean addToGoggleTooltip(List<Component> tooltip, boolean isPlayerSneaking) {
        tooltip.add(Component.literal("    ").append(Component.translatable(getBlockState().getBlock().getDescriptionId()).withStyle(net.minecraft.ChatFormatting.GOLD)));
        
        tooltip.add(Component.literal("  ").append(Component.translatable("rocketnautics.goggles.status")).append(": ")
                .append(isActive() ? Component.translatable("rocketnautics.goggles.active").withStyle(net.minecraft.ChatFormatting.GREEN) : Component.translatable("rocketnautics.goggles.inactive").withStyle(net.minecraft.ChatFormatting.RED)));
        
        int power = getCurrentPower();
        tooltip.add(Component.literal("  ").append(Component.translatable("rocketnautics.goggles.thrust")).append(": ")
                .append(Component.literal(power * 10 + " N").withStyle(net.minecraft.ChatFormatting.GOLD)));
        
        if (fuelTank.getFluidAmount() > 0) {
            tooltip.add(Component.literal("  ").append(Component.translatable("rocketnautics.goggles.fuel")).append(": ")
                    .append(Component.literal(fuelTank.getFluidAmount() + " mB").withStyle(net.minecraft.ChatFormatting.AQUA)));
        }

        if (isActive()) {
            tooltip.add(Component.literal("  ").append(Component.translatable("rocketnautics.goggles.fuel_usage")).append(": ")
                    .append(Component.literal(currentFuelUsage + " mB/t").withStyle(net.minecraft.ChatFormatting.RED)));
        }
        
        return true;
    }
}
